### ISSUE TITLE
Which CAD software for PCB you are using?

### ISSUE THREAD

**Issue by dbychkov** [agroza/aif#2]
Hi Alexandru,

Which CAD software for PCB design you are using? I like the design of your PCBs a lot!
Sorry for asking my question here but I could not find you contact information anywhere else. Feel free to delete this issue after you read my message.

Thank you.

**Comment by agroza** [comment]
Hi,

I am using a very old version of Eagle -- I think it's V.7.
All my schematics employ a set of all custom libraries that I designed within the last 20 years, that include resistors, capacitors, integrated circuits and specialized computer chips.
That CAD package version is not very "intelligent" by today's standards but with a lot of manual (hard-)work you can still achieve good results.

If, today, I were to start designing circuits from scratch, I would choose KiCad instead because of its up-to-date, modern features. And best of all, it's free.

Thanks for your interest in these projects!

**Comment by dbychkov** [comment]
Thank you!
